services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    command: python /main.py
  voice_box:
    image: voicevox/voicevox_engine:cpu-latest
    ports:
      - '50021:50021'
