services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    command: python /app/main.py
    restart: always
    depends_on:
      db:
        condition: service_healthy
  voice_box:
    image: voicevox/voicevox_engine:cpu-latest
    ports:
      - '50021:50021'
    restart: always
  db:
    image: postgres:17-bullseye
    environment:
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: bot_pass
      restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
